# =================
# Zedboard Makefile
# =================

BOARD = zedboard

BOARD_MODEL = em.avnet.com:zed:part0:1.0

PART = xc7z020clg484-1

LINUX_REPO = linux-xlnx

LINUX_CONFIG = xilinx_zynq

UBOOT_REPO = u-boot-xlnx

UBOOT_CONFIG = zynq_zed

DTS = zynq-zed

VIVADO = 2015.4

# Include the rest of the make configuration
# which is common for all boards
include ../scripts/Makefrag

