# =================
# Zedboard Makefile
# =================

BOARD_NAME = zedboard

BOARD_MODEL = em.avnet.com:zed:part0:1.0

BOARD_PART = xc7z020clg484-1

LINUX_REPO = linux-xlnx

LINUX_CONFIG = xilinx_zynq

LINUX_DTS = zynq-zed

LINUX_DTB = zynq-zed

UBOOT_REPO = u-boot-xlnx

UBOOT_CONFIG = zynq_zed

# Include the rest of the make configuration
# which is common for all boards
include ../scripts/Makefrag

