# ===================
# Parallella Makefile
# ===================

BOARD = parallella

BOARD_MODEL = none

PART = xc7z020clg400-1

UBOOT_CONFIG = parallella

# Include the rest of the make configuration
# which is common for all boards
include ../scripts/Makefrag

