# ===================
# Parallella Makefile
# ===================

BOARD_NAME = parallella

BOARD_EDITION = kickstarter

BOARD_MODEL = none

BOARD_PART = xc7z020clg400-1

LINUX_REPO = parallella-linux

LINUX_CONFIG = parallella

LINUX_DTS = zynq-parallella1

LINUX_DTB = zynq-parallella-headless

UBOOT_REPO = parallella-uboot

UBOOT_CONFIG = adapteva_parallella

RISCV_CORE_CONFIG = DefaultFPGAConfig

RISCV_CORE_NAME = RV64G

RISCV_DRAM_BASE_RTL = "3\'d1"

RISCV_DRAM_BITS_RTL = 29

RISCV_DRAM_BASE_DTS = 0x20000000

RISCV_DRAM_SIZE_DTS = 0x18000000

RISCV_DRAM_SIZE_LINUX = 384M

# Include the rest of the make configuration
# which is common for all boards
include ../scripts/Makefrag

